### ISSUE TITLE
java.lang.IllegalArgumentException: Can’t link project ‘/path/to/my/project`. Reason: it’s already linked to the IDE project

### ISSUE THREAD

**Issue by yuryfunikov** [grisha9/gmaven-plugin#3]
Error while trying to import a module into a newly created project i got IllegalArgumentException: Reason: it’s already linked to the IDE project. 

Idea version: 2023.2.2
Gmaven version: 232.7

```
java.lang.IllegalArgumentException: Can’t link project ‘/path/to/my/project’. Reason: it’s already linked to the IDE project
	at com.intellij.openapi.externalSystem.settings.AbstractExternalSystemSettings.linkProject(AbstractExternalSystemSettings.java:132)
	at ru.rzn.gmyasoedov.gmaven.wizard.GOpenProjectProvider.attachProjectAndRefresh(GOpenProjectProvider.kt:38)
	at ru.rzn.gmyasoedov.gmaven.wizard.GOpenProjectProvider.linkToExistingProject(GOpenProjectProvider.kt:32)
	at ru.rzn.gmyasoedov.gmaven.wizard.GProjectOpenProcessor.importProjectAfterwards(GProjectOpenProcessor.kt:33)
	at ru.rzn.gmyasoedov.gmaven.wizard.LinkMavenProjectImportBuilder.commit(LinkMavenProjectImportBuilder.kt:54)
	at com.intellij.projectImport.ProjectImportBuilder.commit(ProjectImportBuilder.java:50)
	at com.intellij.ide.util.projectWizard.ProjectBuilder.commit(ProjectBuilder.java:24)
	at com.intellij.ide.util.projectWizard.ProjectBuilder.commit(ProjectBuilder.java:28)
	at com.intellij.ide.actions.ImportModuleAction$Companion.importModule(ImportModuleAction.kt:225)
	at com.intellij.ide.actions.ImportModuleAction$Companion.doCreateFromWizard(ImportModuleAction.kt:185)
	at com.intellij.ide.actions.ImportModuleAction$Companion.doImport(ImportModuleAction.kt:75)
	at com.intellij.ide.actions.ImportModuleAction.doImport(ImportModuleAction.kt)
	at com.intellij.openapi.externalSystem.action.AttachExternalProjectAction.actionPerformed(AttachExternalProjectAction.java:80)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$2(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:520)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by grisha9** [comment]
added experimental flag for this feature - gmaven.settings.linked.modules
For enabled it:
- press double shift 
- insert into input - gmaven.settings.linked.modules
- enable this option
- after that it should work
since 232.8 version

**Comment by yuryfunikov** [comment]
thank you!
